baseURL = "https://bickers.dev/"
languageCode = "en-us"
title = "Max Bickers"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
autoheadingID = false
